# Generated by Django 5.2.1 on 2026-03-27 02:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CCO', 'Chief Compliance Officer'), ('Representative', 'CCO Representative'), ('InternalReviewer', 'Internal Reviewer'), ('ClientManager', 'Client Manager'), ('Viewer', 'Viewer')], default='Viewer', max_length=50, verbose_name='Role')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('department', models.CharField(blank=True, choices=[('Compliance', 'Compliance'), ('Legal', 'Legal'), ('Risk Management', 'Risk Management'), ('Operations', 'Operations'), ('Client Services', 'Client Services'), ('IT', 'Information Technology'), ('Other', 'Other')], max_length=100, verbose_name='Department')),
                ('employee_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Employee ID')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Job Title')),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Account Locked')),
                ('lock_reason', models.TextField(blank=True, verbose_name='Lock Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Activity')),
                ('last_password_change', models.DateTimeField(auto_now=True, verbose_name='Last Password Change')),
                ('login_attempts', models.IntegerField(default=0, verbose_name='Login Attempts')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA Enabled')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Session Key')),
                ('managed_clients', models.JSONField(blank=True, default=list, verbose_name='Managed Clients')),
                ('notification_preferences', models.JSONField(blank=True, default=dict, help_text='JSON field storing user notification preferences', verbose_name='Notification Preferences')),
                ('theme_preferences', models.JSONField(blank=True, default=dict, verbose_name='Theme Preferences')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
                'permissions': [('can_approve_radius', 'Can approve Radius'), ('can_approve_sessions', 'Can approve Sessions'), ('can_approve_client', 'Can approve Client'), ('can_final_approve', 'Can provide final approval'), ('can_delegate', 'Can delegate tasks'), ('can_view_reports', 'Can view reports'), ('can_manage_users', 'Can manage users'), ('can_audit_logs', 'Can view audit logs'), ('can_export_data', 'Can export data')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Department Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Department Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Department Head')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='accounts.department', verbose_name='Parent Department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Role Name')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted', verbose_name='System Role')),
                ('hierarchy_level', models.IntegerField(default=0, help_text='Higher number means higher authority', verbose_name='Hierarchy Level')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('permissions', models.ManyToManyField(blank=True, related_name='custom_roles', to='auth.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['-hierarchy_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_dashboard', models.CharField(default='main', max_length=100, verbose_name='Default Dashboard')),
                ('widget_layout', models.JSONField(blank=True, default=list, verbose_name='Widget Layout')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('email_digest_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='instant', max_length=20, verbose_name='Email Digest Frequency')),
                ('items_per_page', models.IntegerField(choices=[(10, 10), (25, 25), (50, 50), (100, 100)], default=25, verbose_name='Items Per Page')),
                ('date_format', models.CharField(default='Y-m-d', max_length=20, verbose_name='Date Format')),
                ('time_format', models.CharField(default='H:i', max_length=20, verbose_name='Time Format')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Timezone')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=20, verbose_name='Theme')),
                ('sidebar_collapsed', models.BooleanField(default=False, verbose_name='Sidebar Collapsed')),
                ('notification_sound', models.BooleanField(default=True, verbose_name='Notification Sound')),
                ('desktop_notifications', models.BooleanField(default=True, verbose_name='Desktop Notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='Device Type')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Browser')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='Operating System')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Login Time')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Logout Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('locked', 'Account Locked'), ('expired', 'Session Expired')], max_length=20, verbose_name='Status')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name='Failure Reason')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Login Time')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_audits', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Login Audit',
                'verbose_name_plural': 'Login Audits',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['username', '-login_time'], name='accounts_lo_usernam_5bd900_idx'), models.Index(fields=['ip_address'], name='accounts_lo_ip_addr_72bbe8_idx'), models.Index(fields=['status'], name='accounts_lo_status_fb291d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('approval_needed', 'Approval Needed'), ('approval_completed', 'Approval Completed'), ('revision_needed', 'Revision Needed'), ('delegated', 'Delegated'), ('completed', 'Completed'), ('reminder', 'Reminder'), ('system_alert', 'System Alert'), ('comment', 'Comment Added'), ('mention', 'You were mentioned')], max_length=50, verbose_name='Notification Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Link')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_no_user_id_b37b35_idx'), models.Index(fields=['user', 'is_read'], name='accounts_no_user_id_a4ff2e_idx'), models.Index(fields=['expires_at'], name='accounts_no_expires_c7af83_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('approve', 'Approve'), ('reject', 'Reject'), ('delegate', 'Delegate'), ('upload', 'Upload'), ('download', 'Download'), ('login', 'Login'), ('logout', 'Logout')], max_length=50, verbose_name='Action')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model Name')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='Object ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Object Representation')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='accounts_us_user_id_39428d_idx'), models.Index(fields=['action'], name='accounts_us_action_ec31c8_idx'), models.Index(fields=['model_name'], name='accounts_us_model_n_4177fd_idx')],
            },
        ),
    ]
