# Generated by Django 5.2.1 on 2026-03-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Session Key'),
        ),
    ]
