# Generated by Django 5.2.1 on 2026-04-06 20:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('policy', 'Policies and Procedures'), ('flowchart', 'Flowcharts'), ('change_mgmt', 'Change Management'), ('po_box', 'PO Box List'), ('client_approval', 'Clients that Require Approval'), ('disclosure_en', 'Client Disclosure Documents - English'), ('disclosure_es', 'Client Disclosure Documents - Spanish'), ('master_disclosure', 'Master Disclosure Document'), ('letter_artiva', 'RevSpring - Artiva'), ('letter_facs', 'RevSpring - FACS'), ('letter_email', 'RevSpring - Emails'), ('compumail', 'CompuMail - Emails'), ('letter_spanish', 'Spanish Letters'), ('letter_manual', 'Manual Letters'), ('letter_amex', 'Amex Letters'), ('letter_sms', 'LiveVox - SMS'), ('business_layout', 'Layout-fields'), ('business_flags', 'Flags & Disclosures'), ('business_filters', 'FILTERS'), ('vendor_link', 'Vendor Link')], db_index=True, max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('external_url', models.URLField(blank=True, help_text='For 3rd party vendor links')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_latest', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, help_text='Visible to users')),
                ('is_public', models.BooleanField(default=False, help_text='Visible to all users without permission check')),
                ('table_data', models.JSONField(blank=True, default=dict, help_text='JSON data for table views')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('view_permissions', models.ManyToManyField(blank=True, help_text='Users who can view this document (if not public)', related_name='accessible_documents', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentcategory')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('pdf_file', models.FileField(upload_to='documents/versions/%Y/%m/')),
                ('changelog', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='documents.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', 'is_active'], name='documents_d_documen_c85bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_public', 'is_active'], name='documents_d_is_publ_56f406_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='documents_d_created_71dced_idx'),
        ),
    ]
