# Generated by Django 5.2.1 on 2026-03-27 02:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('version_number', models.CharField(max_length=10, verbose_name='Version Number')),
                ('version_date', models.DateTimeField(auto_now_add=True, verbose_name='Version Date')),
                ('version_note', models.TextField(verbose_name='Version Notes')),
                ('version_data', models.JSONField(default=dict, verbose_name='Version Data')),
                ('changes_from_previous', models.TextField(blank=True, verbose_name='Changes from Previous')),
                ('revision_reason', models.CharField(blank=True, max_length=200, verbose_name='Revision Reason')),
                ('pdf_copy', models.FileField(blank=True, null=True, upload_to='letter_versions/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF Copy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('version_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_versions', to=settings.AUTH_USER_MODEL, verbose_name='Version Author')),
            ],
            options={
                'verbose_name': 'Letter Version',
                'verbose_name_plural': 'Letter Versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='letters/documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'png'])], verbose_name='File')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('file_type', models.CharField(max_length=50, verbose_name='File Type')),
                ('document_type', models.CharField(choices=[('Original', 'Original Document'), ('Revision', 'Revision Document'), ('Supporting', 'Supporting Document'), ('Client Response', 'Client Response'), ('Approval Proof', 'Approval Proof'), ('Final', 'Final Approved Version'), ('Legal', 'Legal Document'), ('Other', 'Other')], max_length=50, verbose_name='Document Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('is_current', models.BooleanField(default=False, verbose_name='Is Current Version')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='letters.letterversion', verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Document Attachment',
                'verbose_name_plural': 'Document Attachments',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='RadiusApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned for Changes')], default='Pending', max_length=20, verbose_name='Status')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cco_or_representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radius_approvals', to=settings.AUTH_USER_MODEL, verbose_name='CCO or Representative')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Radius Approval',
                'verbose_name_plural': 'Radius Approvals',
            },
        ),
        migrations.CreateModel(
            name='SessionsApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned for Changes')], default='Pending', max_length=20, verbose_name='Status')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('session_reference', models.CharField(blank=True, max_length=100, verbose_name='Session Reference')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Sessions Approval',
                'verbose_name_plural': 'Sessions Approvals',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('ticket_number', models.CharField(max_length=100, unique=True, verbose_name='Ticket Number')),
                ('open_date', models.DateTimeField(verbose_name='Open Date')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Open', max_length=50, verbose_name='Status')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20, verbose_name='Priority')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Resolution Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtivaLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_code', models.CharField(max_length=100, unique=True, verbose_name='Letter Code')),
                ('creation_type', models.CharField(choices=[('Creation', 'Creation'), ('Revision', 'Revision')], max_length=20, verbose_name='Creation/Revision')),
                ('creation_revision_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation/Revision Date')),
                ('communication_type', models.CharField(choices=[('Letter', 'Letter'), ('Email', 'Email'), ('SMS', 'SMS')], max_length=20, verbose_name='Letter/Email/SMS')),
                ('communication_code', models.CharField(max_length=50, verbose_name='Letter Code')),
                ('regulatory_body', models.CharField(max_length=100, verbose_name='Regulatory Body')),
                ('timing', models.CharField(choices=[('Immediate', 'Immediate (24 hours)'), ('Urgent', 'Urgent (2-3 days)'), ('Standard', 'Standard (5-7 days)'), ('Extended', 'Extended (2+ weeks)')], max_length=50, verbose_name='Timing')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20, verbose_name='Priority')),
                ('document_description', models.TextField(verbose_name='Document Description')),
                ('production_date', models.DateField(verbose_name='Production Date')),
                ('source', models.CharField(max_length=200, verbose_name='Source')),
                ('letter_description', models.TextField(verbose_name='Letter Description')),
                ('system_type', models.CharField(choices=[('FACS', 'FACS System'), ('ARTIVA', 'Artiva System')], max_length=20, verbose_name='System Type')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Internal_Work', 'Internal Work'), ('Radius_Pending', 'Radius Approval Pending'), ('Sessions_Pending', 'Sessions Approval Pending'), ('Client_Pending', 'Client Approval Pending'), ('CCO_Review', 'CCO Final Review'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Archived', 'Archived')], default='Draft', max_length=50, verbose_name='Status')),
                ('current_version', models.CharField(default='V.0', max_length=10, verbose_name='Current Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('artiva_reference', models.CharField(blank=True, max_length=100, verbose_name='Artiva Reference')),
                ('artiva_category', models.CharField(blank=True, max_length=100, verbose_name='Artiva Category')),
                ('artiva_sub_category', models.CharField(blank=True, max_length=100, verbose_name='Artiva Sub-Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_letters', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('delegated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_delegated_letters', to=settings.AUTH_USER_MODEL, verbose_name='Delegated To')),
            ],
            options={
                'verbose_name': 'Artiva Letter',
                'verbose_name_plural': 'Artiva Letters',
                'indexes': [models.Index(fields=['artiva_reference'], name='letters_art_artiva__134738_idx'), models.Index(fields=['artiva_category'], name='letters_art_artiva__4a957b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('approve', 'Approve'), ('reject', 'Reject'), ('delegate', 'Delegate'), ('upload', 'Upload'), ('download', 'Download'), ('version_create', 'Version Created'), ('status_change', 'Status Changed')], max_length=50, verbose_name='Action')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action'], name='letters_aud_action_fcbd60_idx'), models.Index(fields=['timestamp'], name='letters_aud_timesta_36797f_idx'), models.Index(fields=['user'], name='letters_aud_user_id_d7a1f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.TextField(verbose_name='Comment')),
                ('is_internal', models.BooleanField(default=False, help_text='Visible only to internal users', verbose_name='Internal Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='letters.comment', verbose_name='Parent Comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['created_at'], name='letters_com_created_f02ddd_idx'), models.Index(fields=['author'], name='letters_com_author__b0affd_idx')],
            },
        ),
        migrations.CreateModel(
            name='FACSLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_code', models.CharField(max_length=100, unique=True, verbose_name='Letter Code')),
                ('creation_type', models.CharField(choices=[('Creation', 'Creation'), ('Revision', 'Revision')], max_length=20, verbose_name='Creation/Revision')),
                ('creation_revision_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation/Revision Date')),
                ('communication_type', models.CharField(choices=[('Letter', 'Letter'), ('Email', 'Email'), ('SMS', 'SMS')], max_length=20, verbose_name='Letter/Email/SMS')),
                ('communication_code', models.CharField(max_length=50, verbose_name='Letter Code')),
                ('regulatory_body', models.CharField(max_length=100, verbose_name='Regulatory Body')),
                ('timing', models.CharField(choices=[('Immediate', 'Immediate (24 hours)'), ('Urgent', 'Urgent (2-3 days)'), ('Standard', 'Standard (5-7 days)'), ('Extended', 'Extended (2+ weeks)')], max_length=50, verbose_name='Timing')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20, verbose_name='Priority')),
                ('document_description', models.TextField(verbose_name='Document Description')),
                ('production_date', models.DateField(verbose_name='Production Date')),
                ('source', models.CharField(max_length=200, verbose_name='Source')),
                ('letter_description', models.TextField(verbose_name='Letter Description')),
                ('system_type', models.CharField(choices=[('FACS', 'FACS System'), ('ARTIVA', 'Artiva System')], max_length=20, verbose_name='System Type')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Internal_Work', 'Internal Work'), ('Radius_Pending', 'Radius Approval Pending'), ('Sessions_Pending', 'Sessions Approval Pending'), ('Client_Pending', 'Client Approval Pending'), ('CCO_Review', 'CCO Final Review'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Archived', 'Archived')], default='Draft', max_length=50, verbose_name='Status')),
                ('current_version', models.CharField(default='V.0', max_length=10, verbose_name='Current Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('client_approvals', models.JSONField(default=dict, verbose_name='Client Approvals')),
                ('facs_reference', models.CharField(blank=True, max_length=100, verbose_name='FACS Reference')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_letters', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('delegated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_delegated_letters', to=settings.AUTH_USER_MODEL, verbose_name='Delegated To')),
            ],
            options={
                'verbose_name': 'FACS Letter',
                'verbose_name_plural': 'FACS Letters',
                'indexes': [models.Index(fields=['facs_reference'], name='letters_fac_facs_re_e6c6e4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='letterversion',
            index=models.Index(fields=['version_number'], name='letters_let_version_0ef58b_idx'),
        ),
        migrations.AddIndex(
            model_name='letterversion',
            index=models.Index(fields=['version_date'], name='letters_let_version_c34d2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='letterversion',
            unique_together={('content_type', 'object_id', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['document_type'], name='letters_doc_documen_7d0422_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['upload_date'], name='letters_doc_upload__abb8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['is_current'], name='letters_doc_is_curr_80c587_idx'),
        ),
        migrations.AddIndex(
            model_name='radiusapproval',
            index=models.Index(fields=['approval_status'], name='letters_rad_approva_268baf_idx'),
        ),
        migrations.AddIndex(
            model_name='radiusapproval',
            index=models.Index(fields=['approval_date'], name='letters_rad_approva_f14d2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='radiusapproval',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='sessionsapproval',
            index=models.Index(fields=['approval_status'], name='letters_ses_approva_aa5df5_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionsapproval',
            index=models.Index(fields=['approval_date'], name='letters_ses_approva_e9eb27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionsapproval',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='letters_tic_ticket__c65945_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='letters_tic_status_1549c3_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['open_date'], name='letters_tic_open_da_966d58_idx'),
        ),
    ]
