# Generated by Django 5.2.1 on 2026-03-27 02:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalArtivaLetters',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('letter_code', models.CharField(db_index=True, max_length=100, verbose_name='Letter Code')),
                ('creation_type', models.CharField(choices=[('Creation', 'Creation'), ('Revision', 'Revision')], max_length=20, verbose_name='Creation/Revision')),
                ('creation_revision_date', models.DateTimeField(blank=True, editable=False, verbose_name='Creation/Revision Date')),
                ('communication_type', models.CharField(choices=[('Letter', 'Letter'), ('Email', 'Email'), ('SMS', 'SMS')], max_length=20, verbose_name='Letter/Email/SMS')),
                ('communication_code', models.CharField(max_length=50, verbose_name='Letter Code')),
                ('regulatory_body', models.CharField(max_length=100, verbose_name='Regulatory Body')),
                ('timing', models.CharField(choices=[('Immediate', 'Immediate (24 hours)'), ('Urgent', 'Urgent (2-3 days)'), ('Standard', 'Standard (5-7 days)'), ('Extended', 'Extended (2+ weeks)')], max_length=50, verbose_name='Timing')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20, verbose_name='Priority')),
                ('document_description', models.TextField(verbose_name='Document Description')),
                ('production_date', models.DateField(verbose_name='Production Date')),
                ('source', models.CharField(max_length=200, verbose_name='Source')),
                ('letter_description', models.TextField(verbose_name='Letter Description')),
                ('system_type', models.CharField(choices=[('FACS', 'FACS System'), ('ARTIVA', 'Artiva System')], max_length=20, verbose_name='System Type')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Internal_Work', 'Internal Work'), ('Radius_Pending', 'Radius Approval Pending'), ('Sessions_Pending', 'Sessions Approval Pending'), ('Client_Pending', 'Client Approval Pending'), ('CCO_Review', 'CCO Final Review'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Archived', 'Archived')], default='Draft', max_length=50, verbose_name='Status')),
                ('current_version', models.CharField(default='V.0', max_length=10, verbose_name='Current Version')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('artiva_reference', models.CharField(blank=True, max_length=100, verbose_name='Artiva Reference')),
                ('artiva_category', models.CharField(blank=True, max_length=100, verbose_name='Artiva Category')),
                ('artiva_sub_category', models.CharField(blank=True, max_length=100, verbose_name='Artiva Sub-Category')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('delegated_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Delegated To')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Artiva Letter',
                'verbose_name_plural': 'historical Artiva Letters',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFACSLetters',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('letter_code', models.CharField(db_index=True, max_length=100, verbose_name='Letter Code')),
                ('creation_type', models.CharField(choices=[('Creation', 'Creation'), ('Revision', 'Revision')], max_length=20, verbose_name='Creation/Revision')),
                ('creation_revision_date', models.DateTimeField(blank=True, editable=False, verbose_name='Creation/Revision Date')),
                ('communication_type', models.CharField(choices=[('Letter', 'Letter'), ('Email', 'Email'), ('SMS', 'SMS')], max_length=20, verbose_name='Letter/Email/SMS')),
                ('communication_code', models.CharField(max_length=50, verbose_name='Letter Code')),
                ('regulatory_body', models.CharField(max_length=100, verbose_name='Regulatory Body')),
                ('timing', models.CharField(choices=[('Immediate', 'Immediate (24 hours)'), ('Urgent', 'Urgent (2-3 days)'), ('Standard', 'Standard (5-7 days)'), ('Extended', 'Extended (2+ weeks)')], max_length=50, verbose_name='Timing')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20, verbose_name='Priority')),
                ('document_description', models.TextField(verbose_name='Document Description')),
                ('production_date', models.DateField(verbose_name='Production Date')),
                ('source', models.CharField(max_length=200, verbose_name='Source')),
                ('letter_description', models.TextField(verbose_name='Letter Description')),
                ('system_type', models.CharField(choices=[('FACS', 'FACS System'), ('ARTIVA', 'Artiva System')], max_length=20, verbose_name='System Type')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Internal_Work', 'Internal Work'), ('Radius_Pending', 'Radius Approval Pending'), ('Sessions_Pending', 'Sessions Approval Pending'), ('Client_Pending', 'Client Approval Pending'), ('CCO_Review', 'CCO Final Review'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Archived', 'Archived')], default='Draft', max_length=50, verbose_name='Status')),
                ('current_version', models.CharField(default='V.0', max_length=10, verbose_name='Current Version')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('client_approvals', models.JSONField(default=dict, verbose_name='Client Approvals')),
                ('facs_reference', models.CharField(blank=True, max_length=100, verbose_name='FACS Reference')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('delegated_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Delegated To')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical FACS Letter',
                'verbose_name_plural': 'historical FACS Letters',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
