# Generated by Django 5.2.1 on 2026-03-28 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_historicalartivaletters_historicalfacsletters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='facsletters',
            name='letters_fac_facs_re_e6c6e4_idx',
        ),
        migrations.RemoveField(
            model_name='facsletters',
            name='facs_reference',
        ),
        migrations.RemoveField(
            model_name='historicalfacsletters',
            name='facs_reference',
        ),
        migrations.AddField(
            model_name='facsletters',
            name='communication_subtype',
            field=models.CharField(choices=[('Letter', 'Letter'), ('Email', 'Email'), ('SMS', 'SMS')], default='Letter', max_length=20, verbose_name='Letter/Email/SMS'),
        ),
        migrations.AddField(
            model_name='facsletters',
            name='regulatory',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, verbose_name='Regulatory'),
        ),
        migrations.AddField(
            model_name='facsletters',
            name='ticket_completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket Completed Date'),
        ),
        migrations.AddField(
            model_name='facsletters',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ticket #'),
        ),
        migrations.AddField(
            model_name='facsletters',
            name='ticket_open_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket Open Date'),
        ),
        migrations.AddField(
            model_name='historicalfacsletters',
            name='communication_subtype',
            field=models.CharField(choices=[('Letter', 'Letter'), ('Email', 'Email'), ('SMS', 'SMS')], default='Letter', max_length=20, verbose_name='Letter/Email/SMS'),
        ),
        migrations.AddField(
            model_name='historicalfacsletters',
            name='regulatory',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, verbose_name='Regulatory'),
        ),
        migrations.AddField(
            model_name='historicalfacsletters',
            name='ticket_completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket Completed Date'),
        ),
        migrations.AddField(
            model_name='historicalfacsletters',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ticket #'),
        ),
        migrations.AddField(
            model_name='historicalfacsletters',
            name='ticket_open_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket Open Date'),
        ),
        migrations.AlterField(
            model_name='facsletters',
            name='source',
            field=models.CharField(choices=[('Internal', 'Internal'), ('LiveVox', 'LiveVox'), ('CompuMail', 'CompuMail')], default='Internal', max_length=200, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='facsletters',
            name='timing',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Subsequent', 'Subsequent'), ('Seasonal', 'Seasonal')], default='Initial', max_length=50, verbose_name='Timing'),
        ),
        migrations.AlterField(
            model_name='historicalfacsletters',
            name='source',
            field=models.CharField(choices=[('Internal', 'Internal'), ('LiveVox', 'LiveVox'), ('CompuMail', 'CompuMail')], default='Internal', max_length=200, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='historicalfacsletters',
            name='timing',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Subsequent', 'Subsequent'), ('Seasonal', 'Seasonal')], default='Initial', max_length=50, verbose_name='Timing'),
        ),
        migrations.AddIndex(
            model_name='facsletters',
            index=models.Index(fields=['regulatory'], name='letters_fac_regulat_307578_idx'),
        ),
        migrations.AddIndex(
            model_name='facsletters',
            index=models.Index(fields=['timing'], name='letters_fac_timing_ebdfee_idx'),
        ),
        migrations.AddIndex(
            model_name='facsletters',
            index=models.Index(fields=['source'], name='letters_fac_source_1a615a_idx'),
        ),
    ]
