# Generated by Django 5.2.1 on 2026-03-29 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_remove_facsletters_letters_fac_facs_re_e6c6e4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='artivaletters',
            name='letters_art_artiva__134738_idx',
        ),
        migrations.RemoveIndex(
            model_name='artivaletters',
            name='letters_art_artiva__4a957b_idx',
        ),
        migrations.RemoveField(
            model_name='artivaletters',
            name='artiva_category',
        ),
        migrations.RemoveField(
            model_name='artivaletters',
            name='artiva_reference',
        ),
        migrations.RemoveField(
            model_name='artivaletters',
            name='artiva_sub_category',
        ),
        migrations.RemoveField(
            model_name='historicalartivaletters',
            name='artiva_category',
        ),
        migrations.RemoveField(
            model_name='historicalartivaletters',
            name='artiva_reference',
        ),
        migrations.RemoveField(
            model_name='historicalartivaletters',
            name='artiva_sub_category',
        ),
        migrations.AddField(
            model_name='artivaletters',
            name='communication_subtype',
            field=models.CharField(blank=True, choices=[('Letter', 'Letter'), ('Email', 'Email'), ('SMS', 'SMS')], default='', max_length=20, verbose_name='Letter/Email/SMS'),
        ),
        migrations.AddField(
            model_name='artivaletters',
            name='regulatory',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, verbose_name='Regulatory'),
        ),
        migrations.AddField(
            model_name='artivaletters',
            name='ticket_completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket Completed Date'),
        ),
        migrations.AddField(
            model_name='artivaletters',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ticket #'),
        ),
        migrations.AddField(
            model_name='artivaletters',
            name='ticket_open_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket Open Date'),
        ),
        migrations.AddField(
            model_name='historicalartivaletters',
            name='communication_subtype',
            field=models.CharField(blank=True, choices=[('Letter', 'Letter'), ('Email', 'Email'), ('SMS', 'SMS')], default='', max_length=20, verbose_name='Letter/Email/SMS'),
        ),
        migrations.AddField(
            model_name='historicalartivaletters',
            name='regulatory',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, verbose_name='Regulatory'),
        ),
        migrations.AddField(
            model_name='historicalartivaletters',
            name='ticket_completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket Completed Date'),
        ),
        migrations.AddField(
            model_name='historicalartivaletters',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ticket #'),
        ),
        migrations.AddField(
            model_name='historicalartivaletters',
            name='ticket_open_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket Open Date'),
        ),
        migrations.AlterField(
            model_name='artivaletters',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='artivaletters',
            name='source',
            field=models.CharField(blank=True, choices=[('Internal', 'Internal'), ('LiveVox', 'LiveVox'), ('CompuMail', 'CompuMail')], default='', max_length=200, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='artivaletters',
            name='timing',
            field=models.CharField(blank=True, choices=[('Initial', 'Initial'), ('Subsequent', 'Subsequent'), ('Seasonal', 'Seasonal')], default='', max_length=50, verbose_name='Timing'),
        ),
        migrations.AlterField(
            model_name='facsletters',
            name='communication_subtype',
            field=models.CharField(choices=[('Letter', 'Letter'), ('Email', 'Email'), ('SMS', 'SMS')], default='', max_length=20, verbose_name='Letter/Email/SMS'),
        ),
        migrations.AlterField(
            model_name='facsletters',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='facsletters',
            name='regulatory',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, verbose_name='Regulatory'),
        ),
        migrations.AlterField(
            model_name='facsletters',
            name='source',
            field=models.CharField(choices=[('Internal', 'Internal'), ('LiveVox', 'LiveVox'), ('CompuMail', 'CompuMail')], default='', max_length=200, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='facsletters',
            name='timing',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Subsequent', 'Subsequent'), ('Seasonal', 'Seasonal')], default='', max_length=50, verbose_name='Timing'),
        ),
        migrations.AlterField(
            model_name='historicalartivaletters',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='historicalartivaletters',
            name='source',
            field=models.CharField(blank=True, choices=[('Internal', 'Internal'), ('LiveVox', 'LiveVox'), ('CompuMail', 'CompuMail')], default='', max_length=200, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='historicalartivaletters',
            name='timing',
            field=models.CharField(blank=True, choices=[('Initial', 'Initial'), ('Subsequent', 'Subsequent'), ('Seasonal', 'Seasonal')], default='', max_length=50, verbose_name='Timing'),
        ),
        migrations.AlterField(
            model_name='historicalfacsletters',
            name='communication_subtype',
            field=models.CharField(choices=[('Letter', 'Letter'), ('Email', 'Email'), ('SMS', 'SMS')], default='', max_length=20, verbose_name='Letter/Email/SMS'),
        ),
        migrations.AlterField(
            model_name='historicalfacsletters',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='historicalfacsletters',
            name='regulatory',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, verbose_name='Regulatory'),
        ),
        migrations.AlterField(
            model_name='historicalfacsletters',
            name='source',
            field=models.CharField(choices=[('Internal', 'Internal'), ('LiveVox', 'LiveVox'), ('CompuMail', 'CompuMail')], default='', max_length=200, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='historicalfacsletters',
            name='timing',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Subsequent', 'Subsequent'), ('Seasonal', 'Seasonal')], default='', max_length=50, verbose_name='Timing'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='', max_length=20, verbose_name='Priority'),
        ),
        migrations.AddIndex(
            model_name='artivaletters',
            index=models.Index(fields=['regulatory'], name='letters_art_regulat_b68d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='artivaletters',
            index=models.Index(fields=['timing'], name='letters_art_timing_d4e1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='artivaletters',
            index=models.Index(fields=['source'], name='letters_art_source_f798d3_idx'),
        ),
    ]
