# Generated by Django 5.2.1 on 2026-03-29 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_remove_artivaletters_letters_art_artiva__134738_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiusapproval',
            name='cco_or_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radius_approvals', to=settings.AUTH_USER_MODEL, verbose_name='CCO or Representative'),
        ),
    ]
