# Generated by Django 5.2.1 on 2026-03-29 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0006_alter_radiusapproval_cco_or_representative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiusapproval',
            name='cco_or_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radius_approvals', to=settings.AUTH_USER_MODEL, verbose_name='CCO or Representative'),
        ),
    ]
