# Generated by Django 5.2.1 on 2026-04-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0007_alter_radiusapproval_cco_or_representative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artivaletters',
            name='regulatory_body',
        ),
        migrations.RemoveField(
            model_name='facsletters',
            name='regulatory_body',
        ),
        migrations.RemoveField(
            model_name='historicalartivaletters',
            name='regulatory_body',
        ),
        migrations.RemoveField(
            model_name='historicalfacsletters',
            name='regulatory_body',
        ),
    ]
